### ISSUE TITLE
set_wp does not handle negative longitude

### ISSUE THREAD

**Issue by FabianSchwartau** [nik012003/OpenGS#2]
The title basically says it all. I get:

> Traceback (most recent call last):
>   File "rc.py", line 8, in <module>
>     copter.set_wp(1, 1, 50.9103311, -10.5349744, 0, 10, 0, 0, 0)
>   File "MSP.py", line 194, in set_wp
>     payload += int(lon * 10000000).to_bytes(4, byteorder='little')#lon
> OverflowError: can't convert negative int to unsigned

**Comment by nik012003** [comment]
Hi, thanks for pointing out this issue.

> typedef struct {
    uint8_t action;
    int32_t lat;
    int32_t lon;
    int32_t alt;
    int16_t p1, p2, p3;
    uint8_t flag;
} navWaypoint_t;

lat, lon, alt variables are signed int but in the OpenGS code they are treated as unsigned.
You'd need to add  signed=True in the to_bytes function.Like this:

> payload += int(lon * 10000000).to_bytes(4, byteorder='little', signed=True)

I hope this fixes your problem. Unfortunately I cannot test it/ upload new code now as I won't be home for a few days.
